variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch
  GIT_LFS_SKIP_SMUDGE: 0

stages:
  - validate

validate-textures:
  stage: validate
  image: adamrehn/ue5-full:5.6
  tags:
    - docker
    - linux
  script:
    - echo "Running UE validation..."
    - ue4cli configure --project=C:\Unreal\Projects\assetimportvalidator_ue5_plugin\assetvalidate_plugin.uproject
    - UnrealEditor assetvalidate_plugin.uproject -run=pythonscript -script="Content/Python/CI_AssetValidator.py" -nullrhi -unattended -stdout -NoLogTimes -log
  artifacts:
    paths:
      - Saved/Logs/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'